### ISSUE TITLE
Electoral map: What is our threshold for showing that someone is "leading" in a state?

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16-general#11]
We've talked about a few different colored-in states for the results map:
- No results
- Results coming in but no call
- D-Win
- R-Win
- D-Leading
- R-Leading

There's some concern about showing D/R-Leading as soon as results come in b/c it might be misleading. What should the threshold be, then, for showing that someone is leading in a given state? Or is it preferable to ONLY show that results are coming in (with full results available in a tooltip / state detail page)?

**Comment by TylerFisher** [comment]
This issue was moved to nprapps/elections16graphics#10
