### ISSUE TITLE
Account for possible NE and ME electoral vote splits

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16-general#15]
In most cases, we'll display the results of the statewide vote and can treat NE and ME the same as other states. But where we show Electoral College totals, we'll need to sort out how to 1) determine and 2) display any difference.

Relevant to:
- Electoral vote map
- Electoral College vote totals
- Race-calling

**Comment by TylerFisher** [comment]
I'm getting district level data and passing it to `presidential-national.json` and the county files where applicable.

**Comment by TylerFisher** [comment]
I think we got this.
