### ISSUE TITLE
What House races/ballot measures are we tracking?

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections16-general#18]

**Comment by alykat** [comment]
The briefing book identifies key ballot initiatives, but doesn't appear to get into key House races.

**Comment by TylerFisher** [comment]
Domenico/Jessica Taylor will get us a list by Wednesday.

**Comment by TylerFisher** [comment]
Got the House list. AP only returns 44 ballot measures at the national level, so I think we can just run with those 44. There are more listed in the briefing book, but we're not going to be able to get data for them.
