### ISSUE TITLE
JSON output: NPR-approved winner

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16-general#21]
Current `winner` flag is just the AP call. Anywhere I display winner data in graphics, I would have to check against `call.accept_ap` and `call.override_winner` to know whether it's a valid call. It would be ideal if there was a winner flag in the JSON with the NPR-sanctioned call. (One fewer point of failure.)

**Comment by TylerFisher** [comment]
Fixed in 312b3ce0fd3df7f7f036523899e5ebfda963f685
