### ISSUE TITLE
Get Census/BLS/historical election data

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections16-general#5]

**Comment by brmayes** [comment]
**CB Tables IDs**
Age and Sex: S0101
Race: B02001
Commute: S0801
Education level: S1501
Population: B01003
Veterans: S2101
Immigrants: B05001
Disability status: S1810
Employment (16+); Poverty Status: S2301

**Comment by alykat** [comment]
Possible to get median income by county, too?

**Comment by alykat** [comment]
Per Domenico, data to pull for the county results pages:
- Total population
- % White
- % Black
- % Hispanic
- 2012 result (winning party + percentage point margin)
- Foreclosure rate (maybe "Homes foreclosed per 10k" from [Zillow](http://www.zillow.com/research/data/)? [HUD](https://www.huduser.gov/portal/datasets/nsp_foreclosure_data.html) also has data; unclear how old it is. [RealtyTrac](http://www.realtytrac.com/statsandtrends/foreclosuretrends) also has this but I don't see a download)
- Median income
- Unemployment rate
- % w/ a bachelor's degree or above
